# Generated by Django 4.2.7 on 2025-04-29 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='study_notes',
            new_name='ai_generated_notes',
        ),
        migrations.RenameField(
            model_name='userprogress',
            old_name='last_updated',
            new_name='last_activity',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_type',
            field=models.CharField(choices=[('practice', 'Practice Quiz'), ('video', 'Video Tutorial')], default='practice', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('user', 'tutorial')},
        ),
    ]
