# Generated by Django 4.2.7 on 2025-04-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_rename_study_notes_tutorial_ai_generated_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['topic', 'id'], 'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutorials'},
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='topic',
            field=models.CharField(choices=[('image_segmentation', 'Image Segmentation'), ('edge_detection', 'Edge Detection'), ('clustering', 'Clustering Methods'), ('thresholding', 'Thresholding Techniques'), ('region_growing', 'Region Growing'), ('general', 'General Topics')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
