# Generated by Django 4.2.7 on 2025-05-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_tutorial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('multiple-select', 'Multiple Select'), ('true-false', 'True or False')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='topic',
            field=models.CharField(choices=[('image_segmentation', 'Image Segmentation'), ('edge_detection', 'Edge Detection'), ('clustering', 'Clustering Methods'), ('thresholding', 'Thresholding Techniques'), ('region_growing', 'Region Growing'), ('tnm', 'TNM Staging'), ('general', 'General Topics')], default='general', max_length=30),
        ),
    ]
