# Generated by Django 4.2.7 on 2025-04-08 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import segmentation.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "nifti_file",
                    models.FileField(upload_to=segmentation.models.nifti_file_path),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=segmentation.models.segmentation_result_path,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lung_volume",
                    models.FloatField(
                        blank=True,
                        help_text="Total lung volume in cubic centimeters",
                        null=True,
                    ),
                ),
                (
                    "lesion_volume",
                    models.FloatField(
                        blank=True,
                        help_text="Total lesion volume in cubic centimeters",
                        null=True,
                    ),
                ),
                (
                    "lesion_count",
                    models.IntegerField(
                        blank=True, help_text="Number of distinct lesions", null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="Model confidence score (0-1)", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segmentation_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmentation Task",
                "verbose_name_plural": "Segmentation Tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
