# Generated by Django 4.2.7 on 2025-04-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_alter_segmentationtask_result_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentationtask',
            name='lung_volume',
        ),
    ]
