# Generated by Django 4.2.7 on 2025-05-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0004_segmentationtask_preview_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentationtask',
            name='preview_file',
        ),
    ]
