# Generated by Django 4.2.7 on 2025-05-19 08:22

from django.db import migrations, models
import segmentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0005_remove_segmentationtask_preview_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentationtask',
            name='lesion_volume',
        ),
        migrations.RemoveField(
            model_name='segmentationtask',
            name='result_file',
        ),
        migrations.AddField(
            model_name='segmentationtask',
            name='lung_segmentation',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=segmentation.models.lung_segmentation_path),
        ),
        migrations.AddField(
            model_name='segmentationtask',
            name='lung_volume',
            field=models.FloatField(blank=True, help_text='Total lung volume in cubic centimeters', null=True),
        ),
        migrations.AddField(
            model_name='segmentationtask',
            name='tumor_segmentation',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=segmentation.models.tumor_segmentation_path),
        ),
        migrations.AddField(
            model_name='segmentationtask',
            name='tumor_volume',
            field=models.FloatField(blank=True, help_text='Total tumor volume in cubic centimeters', null=True),
        ),
    ]
