# Generated by Django 4.2.7 on 2025-05-25 15:19

from django.db import migrations, models
import segmentation.models
import storage


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0006_remove_segmentationtask_lesion_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentationtask',
            name='lung_segmentation',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storage.WSLCompatibleFileStorage(), upload_to=segmentation.models.lung_segmentation_path),
        ),
        migrations.AlterField(
            model_name='segmentationtask',
            name='nifti_file',
            field=models.FileField(storage=storage.WSLCompatibleFileStorage(), upload_to=segmentation.models.nifti_file_path),
        ),
        migrations.AlterField(
            model_name='segmentationtask',
            name='tumor_segmentation',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storage.WSLCompatibleFileStorage(), upload_to=segmentation.models.tumor_segmentation_path),
        ),
    ]
